---
- name: Add a user, change `name:`
  hosts: new_lap
  become: true
  tasks:
    - name: Add a user
      ansible.builtin.user:
        name: dan
        shell: /bin/bash
        groups: sudo
        append: true
        state: present
