---
- name: Install Microsoft Teams
  hosts: new_lap
  become: true

  tasks:
    - name: Install snapd
      ansible.builtin.apt:
        name: snapd
        state: present

    - name: Install Microsoft Teams
      community.general.snap:
        name: teams-for-linux
        state: present
